### ISSUE TITLE
rpcs3 - Emerge fail

### ISSUE THREAD

**Issue by latot** [chaoskagami/chaos-overlay#1]
Hi, here a problem emerging the app, log:

CMake Error at rpcs3/CMakeLists.txt:65 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

```
LLVMConfig.cmake
llvm-config.cmake
```

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

**Comment by latot** [comment]
fix:

> =sys-devel/llvm-3.5.0

**Comment by chaoskagami** [comment]
Thanks for reporting this. Actually, I'm probably going to add this to the mask list until I get it working - I was still working on the ebuild and committed it to stable by mistake (version bumps for other stuff)

I'll plug this into the ebuild and push it. As for any other issues, my PC is dual core so compiling and re-compiling rpcs3 takes a LONG time. Any other reports would be appreciated.

**Comment by chaoskagami** [comment]
I just fixed this in my local repo, it'll be up in the next push.
