### ISSUE TITLE
rpcs3 - Executable not found

### ISSUE THREAD

**Issue by latot** [chaoskagami/chaos-overlay#2]
rpcs3 executable don't is installed in the emerge procces, and don't is listed in the installed files

/usr/games/bin/rpcs3 not found

**Comment by chaoskagami** [comment]
Like I said in the previous report, the rpcs3 ebuild I have here is at the moment all kinds of screwy. I'll hopefully have it fixed by end of tomorrow.

**Comment by chaoskagami** [comment]
This seems to be caused by rpcs3 not providing a valid install target - install takes care of asmjit, but doesn't copy bin/rpcs3 like it's supposed to (since they appear to just do a zip-up type build like ppsspp). It's probably solvable with a dobin.

**Comment by chaoskagami** [comment]
Builds now, and as far as I see, runs. Report any other issues if you find them. Thanks.
