### ISSUE TITLE
RPCS3 - Can't install pkg files

### ISSUE THREAD

**Issue by latot** [chaoskagami/chaos-overlay#3]
Hi again, well the compilation works fine but whn i open the program and i try to install a pkg file i recive this error message:

E PKG Loader: Could not create the installation directory: NPJB00580
! IsDirectory: stat failed on /usr/bin/dev_hdd0/game
! path: /dev_hdd0/game/

i try changing the directories but don't works, i try recompiling out of emerge and it works, and i saw in the folder bin of the git and there are some necessary folders expl:

dev_flash dev_hdd0 dev_hdd1 dev_usb000

i don't know if the files in the bin folder are required by the program.

**Comment by chaoskagami** [comment]
Ugh, they probably are necessary...I'll have to check to see if I can just mess with some env vars, but worst case I'm going to have to do an epatch to redirect that.

This one may take a while.

**Comment by chaoskagami** [comment]
Okay, found the relevant snippet for this:

```
            // TODO: This shouldn't use current dir
            fmt::Replace(mpath, "$(EmulatorDir)", Emu.GetEmulatorPath());
            fmt::Replace(mpath, "$(GameDir)", cwd);
```

is in the file rpcs3/Emu/FS/VFS.cpp . This is obviously an upstream issue, so while it's not my responsibility to fix it, I'll make a hacky patch for this repo and submit a better fix later to them directly. Anyways, this one isn't my fault, but theirs for not having complete vfs code.

**Comment by latot** [comment]
Thanks, I already posted the problem in rpcs3 forum.

**Comment by chaoskagami** [comment]
I've reported this to upstream on github as well with a quick and dirty patch, so hopefully this will be fixed sooner rather than later. Anyways, closing. Not my fault.
