### ISSUE TITLE
Error emerging dev-java/jinput-2.0.6

### ISSUE THREAD

**Issue by latot** [chaoskagami/chaos-overlay#4]
Hi again, this package can't be emerged, log:

Calculating dependencies... done!
[ebuild  N    ~] dev-java/jinput-2.0.6  USE="-source" 
[ebuild  N    ~] dev-java/paulscode-codecwav-20101023  USE="doc -source" 
[ebuild  N    ~] dev-java/paulscode-libraryjavasound-20120107  USE="doc -source" 
[ebuild  N    ~] dev-java/guava-17.0  USE="doc -source" 
[ebuild  N    ~] dev-java/paulscode-codecjorbis-20101123  USE="doc -source" 
[ebuild  N    ~] dev-java/lwjgl-2.9.1  USE="doc -egl -source" 
[ebuild  N    ~] dev-java/paulscode-librarylwjglopenal-20130417  USE="doc -source" 
[ebuild  N    ~] games-action/minecraft-1.2.3  PYTHON_TARGETS="python2_7 python3_3 -python3_4" 

Would you like to merge these packages? [Yes/No] y

> > > Verifying ebuild manifests
> > > 
> > > Emerging (1 of 8) dev-java/jinput-2.0.6::chaos
> > > - Fetching files in the background. To view fetch progress, run
> > > - `tail -f /var/log/emerge-fetch.log` in another terminal.
> > >   Downloading 'http://gentoo.localhost.net.ar/distfiles/jinput-r247.tar.xz'
> > >   --2015-02-01 09:08:38--  http://gentoo.localhost.net.ar/distfiles/jinput-r247.tar.xz
> > >   Resolving gentoo.localhost.net.ar... 200.43.192.20
> > >   Connecting to gentoo.localhost.net.ar|200.43.192.20|:80... connected.
> > >   HTTP request sent, awaiting response... 404 Not Found
> > >   2015-02-01 09:08:38 ERROR 404: Not Found.
> > > 
> > > Downloading 'http://dev.gentooexperimental.org/~chewi/distfiles/jinput-r247.tar.xz'
> > > --2015-02-01 09:08:38--  http://dev.gentooexperimental.org/~chewi/distfiles/jinput-r247.tar.xz
> > > Resolving dev.gentooexperimental.org... 91.191.147.225
> > > Connecting to dev.gentooexperimental.org|91.191.147.225|:80... failed: Connection timed out.
> > > Retrying.

--2015-02-01 09:09:39--  (try: 2)  http://dev.gentooexperimental.org/~chewi/distfiles/jinput-r247.tar.xz
Connecting to dev.gentooexperimental.org|91.191.147.225|:80... failed: Connection timed out.
Retrying.

--2015-02-01 09:10:41--  (try: 3)  http://dev.gentooexperimental.org/~chewi/distfiles/jinput-r247.tar.xz
Connecting to dev.gentooexperimental.org|91.191.147.225|:80... failed: Connection timed out.
Giving up.

Cya.

**Comment by chaoskagami** [comment]
Tarballs disappearing from known places. Ugh. Probably a new version. Will fix asap as long as I don't lose power tomorrow.

See, most of the dev-java section is support for minecraft. Aka, duplicated from java-overlay. I wish I could have avoided this, but repoman doesn't like it.

**Comment by chaoskagami** [comment]
As an additional note, jinput is a very slow moving git repo, so I'm going to rewrite this as a live to make my life easier.

**Comment by chaoskagami** [comment]
Okay, I replaced jinput with a live ebuild working off the git repo. As it turns out, the jinput it was fetching was a modified tarball. Big no-no in gentoo, which java-overlay shouldn't have done. It now works off the git, so all is cool.

If you need jinput for something, go ahead and merge the 9999. Trust me. It's stable. Last commit was in July, 2014: https://github.com/jinput/jinput
