### ISSUE TITLE
dev-java/guava:17 no longer avaible

### ISSUE THREAD

**Issue by puggan** [chaoskagami/chaos-overlay#7]
`equery list -po dev-java/guava:17`

gives zero avaible packages, there is a ":18", but ebuild specify ":17"

**Comment by chaoskagami** [comment]
All the QA errors should be fixed by https://github.com/chaoskagami/chaos-overlay/commit/2b104251f95e094ef3c2e329a4eab4b2f91c92ac.

Whether the minecraft ebuild works or not is another matter entirely; it's a losing battle.
